### ISSUE TITLE
The `-p` option doesn't work on Windows (I think)

### ISSUE THREAD

**Issue by LensPlaysGames** [Sirraide/fchk#2]
![image](https://github.com/Sirraide/fchk/assets/69637718/3dd6f1bc-8ced-48a3-9078-13127ee7ae0c)

Given the following file, `cmp_eq.laye`:
```
// R %lcc --ir %s
// d b [a-zA-Z0-9\.]+

// * main : i32():
// +   $b:
// +     return i32 69
i32 main() => 69;
```
this doesn't work
```sh
D:/Programming/strema/2023/InterceptRewrite/fchk/out/fchk.exe "-p" "//" "-l" "." "-D" "lcc=D:/Programming/strema/2023/InterceptRewrite/bld/lcc.exe" "-P" "re" "-P" "nocap" "D:/Programming/strema/2023/InterceptRewrite/tst/laye/cmp_eq.laye"
```
with the errors seen above regarding not finding an R directive.

Given the following file, `cmp_eq.laye`:
```
// FCHK-PREFIX //
// R %lcc --ir %s
// d b [a-zA-Z0-9\.]+

// * main : i32():
// +   $b:
// +     return i32 69
i32 main() => 69;
```
this **does** work
```sh
D:/Programming/strema/2023/InterceptRewrite/fchk/out/fchk.exe "-l" "." "-D" "lcc=D:/Programming/strema/2023/InterceptRewrite/bld/lcc.exe" "-P" "re" "-P" "nocap" "D:/Programming/strema/2023/InterceptRewrite/tst/laye/cmp_eq.laye"
```

**Comment by LensPlaysGames** [comment]
So I added `FCHK_PREFIX //` to a few of the laye test files, **but** it doesn't take precedence over `-p` (big sad), so I removed line 336 (`PREFIX "//"`), and it turns out now those work. So it seems to definitely almost certainly maybe but probably not be `-p` just isn't working. Or I dunno.

![image](https://github.com/Sirraide/fchk/assets/69637718/3ab30a5c-9a37-4dc1-bcbf-8eb1580c61b7)

**Comment by nashiora** [comment]
![image](https://github.com/Sirraide/fchk/assets/22553694/5c859f77-b071-43dc-945c-8a2502b4c24f)
maybe it's aaaaaaaaaa string_view?

**Comment by LensPlaysGames** [comment]
![image](https://github.com/Sirraide/fchk/assets/69637718/c805a4e4-82b1-4212-9d1b-423ca158bddc)

I fixed it. It's the moving into a string_view part that is probably UB and Windows handled it differently than Linux (as is always the case when UAF bugs are in question). I suggest making `Context::preview` member a `std::string`, **not** a `std::string_view`, as that worked to fix it on my machine, and I can't see it bollocking yours.
